const EVENT_TYPE_ENUM = Object.freeze({
    SELF_CONNECTED: "SELF_CONNECTED",
    CLIENT_CONNECTED: "CLIENT_CONNECTED",
    CLIENT_DISCONNECTED: "CLIENT_DISCONNECTED",
    CLIENT_MESSAGE: "CLIENT_MESSAGE",
  });


  const CATEGORY_ENUM = Object.freeze({
    SERVER: "SERVER",
    ROOM: "ROOM",
    GAME: "GAME"
  })
  
  const ROOM_ENUM = Object.freeze({
    JOIN_ROOM: "JOIN_ROOM",
    CREATE_ROOM: "CREATE_ROOM",
    DELETE_ROOM: "DELETE_ROOM"
  });
  
  const GAME_UPDATE = Object.freeze({
    MOVE_LEFT: "MOVE_LEFT",
    MOVE_RIGHT: "MOVE_RIGHT",
    STOP_MOVE_LEFT: "STOP_MOVE_LEFT",
    STOP_MOVE_RIGHT: "STOP_MOVE_RIGHT",
  });
  
  const GAME_COMMANDS = [
    GAME_UPDATE.MOVE_LEFT,
    GAME_UPDATE.MOVE_RIGHT,
    GAME_UPDATE.STOP_MOVE_LEFT,
    GAME_UPDATE.STOP_MOVE_RIGHT,
  ];