const EVENT_TYPE_ENUM = Object.freeze({
  SELF_CONNECTED: "SELF_CONNECTED",
  CLIENT_CONNECTED: "CLIENT_CONNECTED",
  CLIENT_DISCONNECTED: "CLIENT_DISCONNECTED",
  CLIENT_MESSAGE: "CLIENT_MESSAGE",
});

const CATEGORY_ENUM = Object.freeze({
  SERVER: "SERVER",
  ROOM: "ROOM",
  GAME: "GAME",
  ACCOUNT: "ACCOUNT",
  CHAT: "CHAT"
});

const ACCOUNT_ENUM = Object.freeze({
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
});

const ROOM_ENUM = Object.freeze({
  JOIN_ROOM: "JOIN_ROOM",
  CREATE_ROOM: "CREATE_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",
  DELETE_ROOM: "DELETE_ROOM",
  JOIN_LOBBY: "JOIN_LOBBY",
  START_ROOM: "START_ROOM",
  UPDATE_ROOM_VICTORY_POINTS: "UPDATE_ROOM_VICTORY_POINTS"
});

const GAME_ENUM = Object.freeze({
  MOVE_LEFT: "MOVE_LEFT",
  MOVE_RIGHT: "MOVE_RIGHT",
  STOP_MOVE_LEFT: "STOP_MOVE_LEFT",
  STOP_MOVE_RIGHT: "STOP_MOVE_RIGHT",
  START_GAME: "START_GAME",
  UPDATE_GAME: "UPDATE_GAME",
  BlAST: "BLAST"
});

const CHAT_ENUM = Object.freeze({
  SEND_MESSAGE: "SEND_MESSAGE",
  RECEIVE_MESSAGE: "RECEIVE_MESSAGE"
});